'use strict';
const A=globalThis.Analysis;
let state={...A.defaults},view='overview';
const mats={opc:{name:'OPC',cn:'普通矽酸鹽水泥',color:'#2862a0'},pfa:{name:'PFA',cn:'粉煤灰',color:'#087f8c'},ggbs:{name:'GGBS',cn:'粒化高爐礦渣粉',color:'#bc7130'},msf:{name:'MSF',cn:'微矽粉',color:'#7d65ae'}};
const views=[['overview','年度經營','出貨規模與產品組合'],['plants','分廠比較','方量、單耗與材料結構'],['materials','膠材分析','OPC · PFA · GGBS · MSF'],['quality','配合比監控','設計指標與覆核清單'],['methods','口徑與資料','計算方法及可用範圍']];
const fmt=(x,d=1)=>x===null||x===undefined||!Number.isFinite(x)?'—':x.toLocaleString('zh-HK',{minimumFractionDigits:d,maximumFractionDigits:d});
const pct=x=>x===null?'—':fmt(x*100,1)+'%';
const esc=x=>String(x).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tag=x=>`<span class="tag">${x}</span>`;
function table(headers,rows){rows=rows.map(r=>String(r[0]).includes('無資料')?[r[0],...r.slice(1).map(()=> '未提供')]:r);return rows.length?`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th scope="col">${h}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td${i===0?' class="rowstrong"':''}>${c}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'<div class="empty">沒有符合本表條件的資料。<br>請調整篩選；覆核清單無項目不等於沒有風險。</div>';}
function panel(id,title,purpose,body,note='',formula=''){return `<section class="panel"><header class="panel-head"><h2><span class="num">${id}</span>${title}</h2><p class="purpose"><b>用途：</b>${purpose}</p></header><div class="panel-body">${body}</div>${note?`<div class="readout">${note}</div>`:''}${formula?`<div class="formula">${formula}</div>`:''}</section>`;}
function kpis(items){return `<div class="kpis">${items.map(([label,value,unit,note,color])=>`<article class="kpi" style="--accent:${color||'#2862a0'}"><div class="kpi-label">${label}</div><div class="kpi-value">${value}<small>${unit}</small></div><div class="kpi-note">${note}</div></article>`).join('')}</div>`;}
function hbars(items,unit,color='#2862a0'){if(!items.length)return '<div class="empty">沒有可比較的資料</div>';const max=Math.max(...items.map(x=>x.value),1);return `<div class="hbars">${items.map(x=>`<div class="hbar"><span>${esc(x.label)}</span><div class="track"><div class="fill" style="width:${Math.max(0,x.value/max*100)}%;background:${x.color||color}"></div></div><span class="hbar-val">${fmt(x.value,1)} ${unit}</span></div>`).join('')}</div>`;}
function lineChart(points,series,unit){const W=760,H=280,L=62,R=24,T=24,B=48;const vals=points.flatMap(p=>series.map(s=>p[s.key])).filter(v=>v!==null&&Number.isFinite(v));if(!points.length||!vals.length)return '<div class="empty">沒有可繪製的資料</div>';const max=Math.max(...vals,1)*1.12;const xx=i=>L+i*(W-L-R)/Math.max(1,points.length-1),yy=v=>H-B-v/max*(H-B-T);let svg=`<svg class="chart" role="img" aria-label="${esc(unit)}趨勢圖" viewBox="0 0 ${W} ${H}"><text x="${L}" y="15">${esc(unit)}</text>`;for(let j=0;j<=4;j++){const v=max*j/4,y=yy(v);svg+=`<line x1="${L}" x2="${W-R}" y1="${y}" y2="${y}" stroke="#e5ebf1"/><text x="${L-10}" y="${y+4}" text-anchor="end">${fmt(v,max>100?0:1)}</text>`;}points.forEach((p,i)=>{if(points.length<=12||i%3===0||i===points.length-1)svg+=`<text x="${xx(i)}" y="${H-19}" text-anchor="middle">${esc(/^\d{4}-\d{2}$/.test(p.label)?(points.every(x=>x.label.slice(0,4)===p.label.slice(0,4))?p.label.slice(5)+'月':p.label.slice(2)):p.label)}</text>`;});for(const s of series){let path='',open=false;points.forEach((p,i)=>{if(p[s.key]===null||!Number.isFinite(p[s.key])){open=false;return;}path+=`${open?'L':'M'}${xx(i)},${yy(p[s.key])} `;open=true;});svg+=`<path d="${path}" fill="none" stroke="${s.color}" stroke-width="3" stroke-linejoin="round"/>`;points.forEach((p,i)=>{if(p[s.key]!==null&&Number.isFinite(p[s.key]))svg+=`<circle cx="${xx(i)}" cy="${yy(p[s.key])}" r="4" fill="${s.color}"><title>${esc(p.label)} ${esc(s.name)}：${fmt(p[s.key],2)} ${unit}</title></circle>`;});}return `<div class="legend">${series.map(s=>`<span><i style="background:${s.color}"></i>${esc(s.name)}</span>`).join('')}</div><div class="chart-wrap">${svg}</svg></div>`;}
function composition(groups){return `<div class="legend">${Object.entries(mats).map(([k,m])=>`<span><i style="background:${m.color}"></i>${m.name}</span>`).join('')}</div>${groups.map(g=>`<div class="stack-row"><span>${esc(g.key)}</span><div class="stack">${Object.entries(mats).map(([k,m])=>{const p=g.binder?g[k]/g.binder*100:0;return `<span style="width:${p}%;background:${m.color}" title="${m.name} ${fmt(p,2)}%">${p>=10?fmt(p,1)+'%':''}</span>`;}).join('')}</div></div>`).join('')}`;}
function yearLabel(y){return y===3?'第3年 Q1':`第${y}年 全年`;}
function periodLabel(y){const mm=A.months(y,state.quarter);return !mm.length?'無資料':state.quarter==='all'?(y==3?'1–3月':'1–12月'):`第${state.quarter}季`;}
function select(key,label,opts){return `<div><label for="${key}">${label}</label><select id="${key}" data-filter="${key}">${opts.map(([v,t])=>`<option value="${esc(v)}"${state[key]==v?' selected':''}>${esc(t)}</option>`).join('')}</select></div>`;}
function shell(){document.querySelector('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-mark">C</div><div><strong>混凝土技術管理</strong><small>OPERATIONS ANALYSIS</small></div></div><div class="navlabel">分析報表</div><nav class="nav" aria-label="分析頁面">${views.map(([id,n],i)=>`<button data-view="${id}"${id===view?' class="active" aria-current="page"':''}><span>0${i+1}</span>${n}</button>`).join('')}</nav><div class="sidefoot">資料期間<br><b>第1年 — 第3年 Q1</b><br>合成展示數據<br>4 個示例廠別 · 27 個月<br><br>材料用量為配合比推算值</div></aside><main class="main"><header class="topline"><div><div class="eyebrow">生產經營 / 配合比管理</div><h1 id="page-title"></h1><p id="page-subtitle"></p></div><div class="actions"><button id="print" aria-label="列印當前報表">列印報表</button></div></header><div id="filters"></div><div id="scope" class="scope"></div><div class="demo-banner"><b>SYNTHETIC DEMO DATA</b><span>合成展示數據 · 非真實生產紀錄</span></div><div id="content" aria-live="polite"></div><footer class="footer"><span>作品集公開版：所有數值、代碼、排名與趨勢均為合成示例，不代表任何真實企業。</span><span>質量結果尚待試驗資料補充</span></footer></main></div>`;document.querySelector('#print').onclick=()=>window.print();document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});render();}
function renderFilters(){const grades=[...new Set(A.rows.map(r=>r.grade))].sort((a,b)=>(parseFloat(a)||9999)-(parseFloat(b)||9999));const authorities=[...new Set(A.rows.map(r=>r.authority))].sort();document.querySelector('#filters').innerHTML=`<div class="filters">${select('year','分析年度',[['all','全部年度'],['1','第1年'],['2','第2年'],['3','第3年（只有Q1）']])}${select('quarter','季度範圍',[['all','全年／現有期間'],['1','Q1 · 1–3月'],['2','Q2 · 4–6月'],['3','Q3 · 7–9月'],['4','Q4 · 10–12月']])}${select('plant','生產廠別',[['all','全部廠別'],...A.meta.plants.map(p=>[p,p])])}${select('grade','產品等級',[['all','全部產品'],...grades.map(g=>[g,g==='-'?'其他／未分類':/^\d+$/.test(g)?'Grade '+g:g])])}${select('authority','工程類別',[['all','全部工程類別'],...authorities.map(a=>[a,a])])}${select('material','關注膠材',Object.entries(mats).map(([k,m])=>[k,m.name+' · '+m.cn]))}<button id="reset">重設</button></div>`;document.querySelectorAll('[data-filter]').forEach(e=>e.onchange=()=>{state[e.dataset.filter]=e.value;render();});document.querySelector('#reset').onclick=()=>{state={...A.defaults};render();};}
function overview(rr){const s=A.stats(rr),m=A.material(rr,state.material),annual=A.annual(state),monthly=A.monthly(state);const prev=state.year==='all'?null:annual.find(a=>a.year==state.year);const grades=A.group(rr,'grade').sort((a,b)=>b.volume-a.volume);return kpis([['出貨方量',fmt(s.volume/10000,2),'萬 m³',prev&&prev.yoy!==null?`同可用月份較上年 ${prev.yoy>=0?'+':''}${pct(prev.yoy)}`:'依目前篩選加總出貨量'],['出貨記錄',fmt(s.n,0),'條',`${s.plants} 個廠別 · ${s.mixes} 個配合比編碼`],['理論膠材單耗',fmt(s.unit,2),'kg/m³','已記錄膠材總量 ÷ 出貨量','#087f8c'],[`${mats[state.material].name} 理論單耗`,fmt(m.unit,2),'kg/m³',m.partial?'僅計第2–3年已設欄位資料':'該材料總量 ÷ 全部出貨量',mats[state.material].color]])+`<div class="grid">${panel('01','月度出貨走勢','辨認出貨高低峰，安排生產及材料需求。',lineChart(monthly.map(r=>({label:r.key,volume:r.volume/10000})),[{key:'volume',name:'出貨量',color:'#2862a0'}],'萬 m³'),'方量反映出貨規模；未提供設計產能，不能解讀為產能利用率。')}${panel('02','產品等級分布','看出哪些產品佔用主要生產量，理解單耗差異的背景。',hbars(grades.slice(0,8).map(g=>({label:g.key==='-'?'其他產品':'G '+g.key,value:g.volume/s.volume*100})),'%'),`顯示方量最高的8類；${grades[0]?`首位類別佔 ${pct(grades[0].volume/s.volume)}。`:''}密度型產品及砂漿不可與數字強度等級直接排名。`)}</div>`+panel('03','跨年度經營比較','比較年度規模與單耗；同比按各年度實際可用月份對齊。',table(['年度／期間','出貨量 m³','同期增幅','記錄數','配比數','OPC kg/m³','膠材 kg/m³'],annual.map(a=>[`${a.year}<br><span class="small">${periodLabel(a.year)}</span>`,a.months.length?fmt(a.volume,2):'未提供',pct(a.yoy),fmt(a.n,0),fmt(a.mixes,0),fmt(a.opcUnit,2),fmt(a.unit,2)])),'此表固定比較三個年度，沿用季度、廠別、等級及工程類別篩選。第3年只有Q1，不能與全年總量直接比較。','同比＝本期方量 ÷ 上年相同可用月份方量 − 1；單耗採總量加權，不是每條記錄的簡單平均。')+panel('04','每月經營與膠材明細','把趨勢圖轉成可核對的數值，查看月份、方量及材料需求。',table(['月份','出貨量 m³','記錄數','OPC 噸','PFA 噸','GGBS 噸','MSF 噸','膠材 kg/m³'],monthly.map(g=>[g.key,fmt(g.volume,2),fmt(g.n,0),fmt(g.opc/1000,2),fmt(g.pfa/1000,2),g.key.startsWith('1')?'未設欄位':fmt(g.ggbs/1000,2),fmt(g.msf/1000,2),fmt(g.unit,2)])),'材料量均為理論需求，並非採購收貨、庫存耗用或實際生產計量。');}
function render(){renderFilters();document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('active',b.dataset.view===view);if(b.dataset.view===view)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current');});const v=views.find(v=>v[0]===view);document.querySelector('#page-title').textContent=v[1];document.querySelector('#page-subtitle').textContent=v[2];document.querySelector('#scope').innerHTML=`<strong>目前範圍：</strong>${state.year==='all'?'第1–3年 Q1':yearLabel(+state.year)} · ${state.quarter==='all'?'現有全部月份':'Q'+state.quarter} · ${state.plant==='all'?'全部廠別':state.plant} · ${state.grade==='all'?'全部產品':'等級 '+esc(state.grade)}。關注膠材只切換材料指標，不剔除出貨記錄。`;const rr=A.filter(state);const notice='<div class="notice">材料用量＝配合比單耗 × 出貨量。第3年僅有1–3月；第1年沒有GGBS欄位。質量頁分析設計參數，不代表實測強度或合格判定。</div>';document.querySelector('#content').innerHTML=notice+(view==='overview'?overview(rr):view==='plants'?plantsPage(rr):view==='materials'?materialsPage(rr):view==='quality'?qualityPage(rr):methodsPage());}
function plantsPage(rr){
  const gs=A.group(rr,'plant').sort((a,b)=>b.volume-a.volume),s=A.stats(rr),top=gs[0],focus=mats[state.material];
  const byYear=[1,2,3].flatMap(y=>A.group(A.filter(state,{year:String(y)}),'plant').map(g=>({...g,year:y})));
  const matrix=A.group(rr.filter(r=>/^\d+$/.test(r.grade)),r=>r.plant+'|'+r.grade).sort((a,b)=>b.volume-a.volume);
  return kpis([['有出貨廠別',fmt(gs.length,0),'個','依當前條件實際出貨計數'],['首位廠別',top?top.key:'—','',top?`方量 ${fmt(top.volume/10000,2)} 萬 m³`:'此條件無資料'],['首位廠別佔比',top?pct(top.volume/s.volume):'—','','用於觀察生產集中程度','#087f8c'],['分廠比較基礎',state.grade==='all'?'混合產品':'G '+state.grade,'',state.grade==='all'?'請先篩選同等級，再比較單耗':'同等級仍可能有規格及工程要求差異','#bc7130']])+
  `<div class="grid equal">${panel('01','各廠出貨貢獻','辨認供貨主力與廠別間的出貨分布。',hbars(gs.map(g=>({label:g.key,value:g.volume/10000})),'萬 m³'),'此處反映供貨分工，不是產能、設備效率或盈利能力。')}${panel('02','各廠膠材構成','比較廠別使用OPC與摻合料的配合比結構。',composition(gs),'比例以各廠已記錄膠材總量為分母。配比結構不同，不代表哪一廠質量更好。')}</div>`+
  panel('03','分廠經營與材料單耗表','在同一表查看各廠方量、產品覆蓋、膠材總單耗及關注材料。',table(['廠別','出貨量 m³','方量佔比','記錄數','配比數','OPC kg/m³','膠材 kg/m³',`${focus.name} 噸`,`${focus.name} kg/m³`],gs.map(g=>{const m=A.material(g.items,state.material);return [g.key,fmt(g.volume,2),pct(g.volume/s.volume),fmt(g.n,0),g.mixes,fmt(g.opcUnit,2),fmt(g.unit,2),m.known?fmt(m.mass/1000,2)+(m.partial?' *':''):'未設欄位',fmt(m.unit,2)+(m.partial?' *':'')];})),'* GGBS只統計第2–3年具備欄位的出貨。未先控制等級、工作性及用途，不能用單耗直接評定分廠績效。')+
  panel('04','年度 × 分廠追蹤表','看各廠在不同年度的出貨與材料需求如何改變。',table(['年度','期間','廠別','出貨量 m³','記錄數','OPC 噸','PFA 噸','GGBS 噸','MSF 噸','膠材 kg/m³'],byYear.map(g=>[g.year,periodLabel(g.year),g.key,fmt(g.volume,2),fmt(g.n,0),fmt(g.opc/1000,2),fmt(g.pfa/1000,2),g.year===1?'未設欄位':fmt(g.ggbs/1000,2),fmt(g.msf/1000,2),fmt(g.unit,2)])),'此表固定展示各年度，沿用其餘篩選。某廠某年沒有記錄，不代表該廠尚未建成或沒有產能。')+
  panel('05','分廠 × 等級材料比較','縮小產品等級的影響，定位值得進一步覆核的單耗差異。',table(['廠別／等級','出貨量 m³','記錄數','OPC kg/m³','PFA kg/m³','GGBS kg/m³','MSF kg/m³','膠材 kg/m³'],matrix.map(g=>{const r=g.items[0],m=A.material(g.items,'ggbs');return [r.plant+' / G'+r.grade,fmt(g.volume,2),fmt(g.n,0),fmt(g.opcUnit,2),fmt(g.pfa/g.volume,2),fmt(m.unit,2)+(m.partial?' *':''),fmt(g.msf/g.volume,2),fmt(g.unit,2)];})),'只包括數字強度等級。仍需核對指定坍落度、施工用途、原材料体系及耐久性要求，才可討論配比改善。');
}
function materialsPage(rr){
  const key=state.material,def=mats[key],m=A.material(rr,key),s=A.stats(rr),monthly=A.monthly(state);const annual=A.annual(state);const gs=A.group(rr,'plant');
  const scope=m.partial?'（僅第2–3年）':'';
  const monthlyRows=monthly.map(g=>{const x=A.material(g.items,key);return {...g,mat:x};});
  return kpis([[`${def.name} 理論總用量`,fmt(m.mass===null?null:m.mass/1000,2),'噸',def.cn+scope,def.color],[`${def.name} 全部出貨平均`,fmt(m.unit,2),'kg/m³','材料量 ÷ 有該欄位的全部出貨量',def.color],[`${def.name} 使用產品平均`,fmt(m.usedUnit,2),'kg/m³','材料量 ÷ 實際使用該材料的出貨量',def.color],['材料使用覆蓋率',pct(m.coverage),'','使用該材料方量 ÷ 有欄位的出貨量',def.color]])+
  `<div class="grid">${panel('01',`${def.name} 月度單耗`, '分清材料添加水平變化與產品採用比例變化。',lineChart(monthlyRows.map(g=>({label:g.key,all:g.mat.unit,used:g.mat.usedUnit})),[{key:'all',name:'全部出貨平均',color:def.color},{key:'used',name:'使用產品平均',color:'#91a7bb'}],'kg/m³'),'兩條線分母不同。若使用產品平均接近不變、全部出貨平均上升，可能是採用該材料的產品佔比增加。缺值月份不連線。')}${panel('02',`${def.name} 分廠理論需求`,'看材料需求集中在哪些工廠，支援供應安排。',hbars(gs.map(g=>({label:g.key,value:(A.material(g.items,key).mass||0)/1000,color:def.color})).filter(g=>A.material(gs.find(x=>x.key===g.label).items,key).known),'噸',def.color),key==='ggbs'?'第1年沒有GGBS欄位，已排除；數值不代表倉庫實際領用。':'材料總用量受出貨規模和配比同時影響。')}</div>`+
  panel('03','四類膠材總覽','同時核對材料量、構成、單耗與採用比例，避免單一指標造成誤判。',table(['膠材','理論用量 噸','全部出貨 kg/m³','使用產品 kg/m³','使用方量 m³','覆蓋率','膠材佔比'],Object.entries(mats).map(([k,d])=>{const x=A.material(rr,k);return [d.name+'<br><span class="small">'+d.cn+(x.partial?'・僅第2–3年':'')+'</span>',x.known?fmt(x.mass/1000,2):'未設欄位',fmt(x.unit,2),fmt(x.usedUnit,2),x.known?fmt(x.usedVolume,2):'—',pct(x.coverage),pct(x.binderShare)];})),'第1年膠材合計依已存在的OPC、PFA、MSF欄位計算；跨年含第1年時，GGBS一列採用較短的已知期間，其佔比不可與其他列直接加總。','OPC＝CRC＋GIC。膠材＝已記錄OPC＋PFA＋GGBS＋MSF；kg轉噸除以1,000。')+
  panel('04','年度膠材結構','比較各年度水泥與摻合料的需求及組合變化。',table(['年度／期間','出貨量 m³','OPC 噸','PFA 噸','GGBS 噸','MSF 噸','膠材 kg/m³','摻合料佔比'],annual.map(g=>[g.year+'<br><span class="small">'+periodLabel(g.year)+'</span>',g.months.length?fmt(g.volume,2):'未提供',fmt(g.opc/1000,2),fmt(g.pfa/1000,2),g.year===1?'未設欄位':fmt(g.ggbs/1000,2),fmt(g.msf/1000,2),fmt(g.unit,2),pct(g.scm)])),'此表固定展示三個年度，沿用其餘篩選。摻合料佔比為(PFA＋GGBS＋MSF)／已記錄膠材，不是已核證的減碳比例。')+
  panel('05',`${def.name} 月度核對表`,'查看每月材料總量、採用規模與兩種單耗的實際數字。',table(['月份','總出貨 m³','材料用量 噸','使用方量 m³','全部出貨 kg/m³','使用產品 kg/m³','覆蓋率'],monthlyRows.map(g=>[g.key,fmt(g.volume,2),g.mat.known?fmt(g.mat.mass/1000,2):(g.key.startsWith('1')&&key==='ggbs'?'未設欄位':'—'),g.mat.known?fmt(g.mat.usedVolume,2):'—',fmt(g.mat.unit,2),fmt(g.mat.usedUnit,2),pct(g.mat.coverage)])),'「—」表示沒有有效分母或資料不可得；有出貨而未使用該材料時，总用量為0，使用產品單耗為「—」。');
}
function scatter(groups){
  const good=groups.filter(g=>g.binder>0&&g.water>0&&g.volume>0);if(!good.length)return '<div class="empty">沒有可比較的數字等級配合比</div>';
  const W=760,H=300,L=65,R=25,T=30,B=45;const xs=good.map(g=>g.water/g.binder),ys=good.map(g=>g.unit),xmin=Math.max(0,Math.min(...xs)-.03),xmax=Math.max(...xs)+.03,ymin=Math.max(0,Math.min(...ys)-30),ymax=Math.max(...ys)+30,maxV=Math.max(...good.map(g=>g.volume));const xx=v=>L+(v-xmin)/(xmax-xmin)*(W-L-R),yy=v=>H-B-(v-ymin)/(ymax-ymin)*(H-B-T);let svg=`<svg class="chart" role="img" aria-label="理論水膠比與膠材單耗散點圖" viewBox="0 0 ${W} ${H}"><text x="${L}" y="16">膠材 kg/m³</text>`;for(let i=0;i<=4;i++){const x=xmin+(xmax-xmin)*i/4,y=ymin+(ymax-ymin)*i/4;svg+=`<line x1="${L}" x2="${W-R}" y1="${yy(y)}" y2="${yy(y)}" stroke="#e5ebf1"/><text x="${L-9}" y="${yy(y)+4}" text-anchor="end">${fmt(y,0)}</text><text x="${xx(x)}" y="${H-18}" text-anchor="middle">${fmt(x,2)}</text>`;}good.forEach(g=>{const p=g.items[0].plant,col={'Plant A':'#2862a0','Plant B':'#087f8c','Plant C':'#bc7130','Plant D':'#7d65ae'}[p]||'#2862a0';svg+=`<circle cx="${xx(g.water/g.binder)}" cy="${yy(g.unit)}" r="${4+Math.sqrt(g.volume/maxV)*13}" fill="${col}" fill-opacity=".6" stroke="white" stroke-width="1"><title>${p} ${g.items[0].mix}｜${fmt(g.volume,1)}m³｜理論水膠比${fmt(g.water/g.binder,3)}｜膠材${fmt(g.unit,2)}kg/m³</title></circle>`;});return `<div class="legend"><span>圓點大小＝出貨量；顏色＝廠別；滑鼠停留查看數值</span></div><div class="chart-wrap">${svg}</svg></div><div class="small" style="text-align:right">理論用水／已記錄膠材（質量比）</div>`;
}
function waterfall(d){if(!d.valid)return '<div class="empty">此篩選在第1年及第2年沒有共同可比較的數字等級</div>';const terms=[{name:'等級結構變化',v:d.structure,start:0,c:'#bc7130'},{name:'同等級內變化',v:d.within,start:d.structure,c:'#087f8c'},{name:'合計變化',v:d.total,start:0,c:'#2862a0'}];const low=Math.min(0,d.structure,d.total)-1,high=Math.max(0,d.structure,d.total)+2,W=760,H=260,yy=v=>210-(v-low)/(high-low)*175;let s=`<svg class="chart" role="img" aria-label="單耗变化對稱分解" viewBox="0 0 ${W} ${H}"><text x="55" y="20">OPC kg/m³ 變化</text><line x1="55" x2="735" y1="${yy(0)}" y2="${yy(0)}" stroke="#b8c7d5"/>`;terms.forEach((t,i)=>{const x=115+i*225,y0=yy(t.start),y1=yy(t.start+t.v);s+=`<rect x="${x}" y="${Math.min(y0,y1)}" width="95" height="${Math.max(Math.abs(y1-y0),1)}" fill="${t.c}"/><text x="${x+47}" y="${Math.min(y0,y1)-12}" text-anchor="middle" style="font-size:18px;fill:${t.c};font-weight:700">${t.v>=0?'+':''}${fmt(t.v,2)}</text><text x="${x+47}" y="244" text-anchor="middle">${t.name}</text>`;});return `<div class="chart-wrap">${s}</svg></div>`;}
function qualityPage(rr){
  const selectedGrade=state.grade==='all'?'45':state.grade;const qr=rr.filter(r=>r.grade===selectedGrade&&/^\d+$/.test(r.grade));const s=A.stats(qr);const mixes=A.group(qr,r=>[r.plant,r.mix,r.authority,r.specifiedSlump,r.system].join('|'));const candidates=A.peers(qr).filter(g=>g.gap>0&&g.n>=5).slice(0,12);const d=A.decompose(state);
  const profile=A.group(qr,'plant');
  return `<div class="notice">本頁為「配合比設計監控」，沒有實測強度、實際投料或出廠／到場坍落度，因此不提供合格率、Cpl或實際水膠比。${state.grade==='all'?'為避免混合等級，本頁配合比圖表預設聚焦 Grade 45；可在上方選擇其他等級。':''}</div>`+
  kpis([[`Grade ${selectedGrade} 出貨`,fmt(s.volume/10000,2),'萬 m³','依目前年度、季度、廠別及工程類別'],['設計膠材平均',fmt(s.unit,2),'kg/m³','合計膠材／合計方量','#087f8c'],['理論水膠比',fmt(s.waterBinder,3),'','理論用水總量／已記錄膠材總量','#bc7130'],['實測強度結果','未提供','','須補充試件及7／28天強度資料','#7d65ae']])+
  `<div class="grid equal">${panel('01',`Grade ${selectedGrade} 配合比設計分布`,'找出高膠材或不同理論水膠比的配比，作為技術覆核入口。',scatter(mixes),'每點為廠別、配比、工程類別、指定SLUMP及膠材体系的組合加權平均。不是逐盤實測分布，也不是強度預測。')}${panel('02','第1年 → 第2年 單耗變化分解','區分产品等級占比變化，與同等級內平均單耗變化。',waterfall(d),`此圖固定比較第1年與第2年，沿用季度及其他條件，只取共同數字等級。${d.valid?`可比方量覆蓋：第1年 ${pct(d.coverage0)}，第2年 ${pct(d.coverage1)}。`:''}這是描述性分解，不能歸因於已實現降本。`)}</div>`+
  panel('03',`Grade ${selectedGrade} 分廠設計參數`,'在相同強度等級下比較設計膠材及用水，決定下一步需要核對的條件。',table(['廠別','出貨量 m³','記錄數','OPC kg/m³','摻合料 kg/m³','膠材 kg/m³','理論用水 kg/m³','理論水膠比'],profile.map(g=>[g.key,fmt(g.volume,2),fmt(g.n,0),fmt(g.opcUnit,2),fmt((g.pfa+g.ggbs+g.msf)/g.volume,2),fmt(g.unit,2),fmt(g.water/g.volume,2),fmt(g.waterBinder,3)])),'理論用水沒有砂石含水修正、現場加水及含水測試，不能用來判定實際生產水膠比是否合規。')+
  panel('04','配合比覆核候選清單','找出同組膠材單耗高於中位數、且供貨量較大的配比，安排工程要求及試配資料覆核。',table(['廠別／匿名配比','出貨量 m³','記錄數','同組配比數','膠材 kg/m³','組內中位 kg/m³','高出 kg/m³'],candidates.map(g=>[g.plant+' / '+g.key,fmt(g.volume,1),fmt(g.n,0),g.peers,fmt(g.unit,2),fmt(g.median,2),'+'+fmt(g.gap,2)])),'分組條件：同廠、同等級、同工程類別、同指定SLUMP值、同膠材種類組合；每組至少3個配比，候選至少5條出貨記錄。按方量排序，最多12項。未控制全部工程與材料要求，不能直接減膠材。','組內中位數按各配比的方量加權單耗計算，再對配比取中位數；差值為覆核線索，不是可節約量。無候選表示未符合篩選條件，不等於沒有風險。')+
  panel('05','質量控制資料清單','直接看清現在能監控甚麼，以及要補哪類資料才能形成真正的質量閉環。',`<div class="status-grid">${[['可分析','設計配合比','膠材構成、理論用水、配比及廠別差異'],['可分析','生產任務覆蓋','出貨日期、方量、配比使用及產品結構'],['有限度','版本追溯','原明細有版本號，但材料查庫公式未按版本聯合匹配'],['未提供','強度結果','試件ID、齡期、強度、養護與試驗資料'],['未提供','實際生產計量','逐盤設計／實投、含水修正、人工補水'],['未提供','交付與缺陷','出廠／到場實測、運輸時間、退料及投訴']].map(([st,h,p])=>`<div class="status-item"><span class="status ${st==='可分析'?'':'missing'}">${st}</span><strong>${h}</strong>${p}</div>`).join('')}</div>`,'資料完整性和查庫成功，均不能代替產品質量合格判定。');
}
function methodsPage(){
  return panel('01','這份看板如何使用','先選擇分析範圍，再依經營、分廠、材料和設計監控的順序閱讀。',`<div class="method"><p><b>年度經營：</b>看供貨規模、月度節奏、產品結構與同期增長。</p><p><b>分廠比較：</b>看各廠方量貢獻及材料構成，先選同等級再比較單耗。</p><p><b>膠材分析：</b>選OPC、PFA、GGBS或MSF，區分材料需求、採用率和添加水平。</p><p><b>配合比監控：</b>看設計參數分布及覆核候選，不把理論參數當作實測質量。</p><p>全局筛选适用於各頁；明確標注「固定比較三個年度」的表格只忽略年度選擇，其他篩選照常保留。關注膠材是指标选择，不會改变出貨樣本。</p></div>`)+
  panel('02','指標字典','了解每張表的分子、分母、單位與用途。',table(['指標','計算方式','管理用途'],[
    ['出貨方量','有效明細的出貨量加總，m³','供貨規模；不是設備設計產能'],['出貨記錄數','有效出貨明細條數','資料／任務覆蓋；不等於車次或盤次'],['理論材料用量','配合比庫單耗 × 對應出貨量','估算材料需求；不是實際耗用'],['膠材單耗','已記錄OPC＋PFA＋GGBS＋MSF總量／總出貨量','觀察配合比材料強度'],['全部出貨材料單耗','材料總量／具備該欄位的總出貨量','整體業務的材料需求強度'],['使用產品材料單耗','材料總量／該材料用量大於0的出貨方量','採用該材料產品的添加水平'],['材料使用覆蓋率','使用該材料方量／具備該欄位的全部方量','材料在產品組合中的採用程度'],['摻合料佔比','(PFA＋GGBS＋MSF)／已記錄膠材總量','材料結構；不是合格率或核證減碳率'],['理論水膠比','理論用水總量／已記錄膠材總量','設計配比畫像；不是有效或實際水膠比'],['同比','本期方量／上年相同可用月份方量−1','同期間規模變化'],['—／未設欄位','無有效分母／來源沒有該字段','不同於真實數值0']]))+
  panel('03','公開版資料說明','確認作品集資料的保密邊界與可展示內容。',`<div class="method"><p><b>本網站只含合成數據。</b>所有數值、廠別、工程類別、配比代碼、趨勢與排名均由固定種子的獨立模型生成。</p><p><b>沒有搬運或擾動原始記錄。</b>公開資料不是原始值乘倍率、加噪音或重新排序，因此不能由網站數字反推真實營運表現。</p><p><b>保留的是分析框架。</b>年度、分廠、Grade、工程類別、OPC、PFA、GGBS、MSF、水膠比和同類配比對標等邏輯可供面試官操作。</p></div>`)+
  panel('04','分析邊界與下一步補數','清楚區分示例洞察、工程判斷與尚不能下的結論。',`<div class="method"><p><b>第3年只有第一季度。</b>年度表明確標示1–3月，不能把該總量與全年直接比較。</p><p><b>第1年沒有GGBS欄位。</b>用於展示缺失字段如何處理；跨年GGBS指標只用第2–3年的合成資料。</p><p><b>沒有價格、強度與實際計量。</b>因此不計算實際成本、毛利、強度合格率、Cpk或材料浪費率，也不把理論配比當作質量結果。</p><p><b>年度單耗分解：</b>結構項拆解產品等級佔比變化，等級內項拆解同等級平均單耗變化；兩者相加等於共同等級範圍的總變化。</p><p><b>下一步：</b>若在真實企業落地，需串接配比版本、逐盤實投、含水修正、試件強度、退料及投訴資料，形成質量閉環。</p></div>`)+
  panel('05','脫敏設計','讓面試官看到方法，同時不暴露公司機密。','<div class="method"><p>公開代碼只包含 <b>Plant A–D</b>、<b>Project Type A–E</b> 與 <b>SYN-xxx</b>。年份採第1年／第2年／第3年表示；沒有客戶、地盤、合同、任務編號、原始檔名或真實彙總。</p><p>網站頂部、頁尾及README均標示合成資料，避免將示例洞察誤認為真實企業結論。</p></div>');
}
shell();
// Optional browser-native tools use the same validated state as the visible controls.
function configureDashboard(input){
  if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('需要篩選物件');
  const allowed={year:['all','1','2','3'],quarter:['all','1','2','3','4'],plant:['all',...A.meta.plants],grade:['all',...new Set(A.rows.map(r=>r.grade))],authority:['all',...new Set(A.rows.map(r=>r.authority))],material:Object.keys(mats),view:views.map(v=>v[0])};
  for(const [k,v]of Object.entries(input))if(!allowed[k]||!allowed[k].includes(v))throw new Error('無效篩選：'+k);
  const {view:nextView,...filters}=input;state={...state,...filters};if(nextView)view=nextView;render();return readDashboard();
}
function readDashboard(){const rr=A.filter(state),s=A.stats(rr);return {filters:{...state},view,records:s.n,volume_m3:s.volume,recorded_binder_kg_m3:s.unit,material:A.material(rr,state.material),basis:'理論配合比推算；非實際計量或強度'};}
if(document.modelContext?.registerTool){
  const lifecycle=new AbortController();
  const tools=[{name:'configure_concrete_dashboard',title:'設定混凝土分析篩選',description:'設定頁面與年度、季度、廠別、等級、工程類別及關注膠材，並返回當前摘要。',inputSchema:{type:'object',properties:{year:{type:'string',enum:['all','1','2','3']},quarter:{type:'string',enum:['all','1','2','3','4']},plant:{type:'string',enum:['all',...A.meta.plants]},grade:{type:'string',enum:['all',...new Set(A.rows.map(r=>r.grade))]},authority:{type:'string',enum:['all',...new Set(A.rows.map(r=>r.authority))]},material:{type:'string',enum:Object.keys(mats)},view:{type:'string',enum:views.map(v=>v[0])}},additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:configureDashboard},{name:'read_concrete_summary',title:'讀取當前混凝土分析摘要',description:'讀取當前篩選下的出貨與理論膠材指標，不更改頁面。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>readDashboard()}];
  for(const tool of tools){try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(e=>console.warn('Optional dashboard tool unavailable',e.message));}catch(e){console.warn('Optional dashboard tool unavailable',e.message);}}
  window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

